### ISSUE TITLE
requirements.txt中似乎有很多奇怪的包

### ISSUE THREAD

**Issue by neo1218** [Muxi-Studio/guisheng_be#2]
https://github.com/Muxi-Studio/guisheng_be/blob/master/guisheng/requirement.txt

为啥会有这么多pyobjc的包?  http://pythonhosted.org/pyobjc/
一些不需要的都可以删了
最简单的方法, 重新创建一个venv, 然后跑桂声，报什么错，装什么, 最后

    $pip freeze > requirements.txt

就应该是可以把桂声跑起来的最低配置了.
然后如果不是部署在学校服务器上的话，部署可以考虑docker

**Comment by RoseOu** [comment]
恩..当时直接生成了requirements.txt之后没看它都不知道它有问题，已改。（朱老板code review连requirements.txt都看，感动..）

**Comment by neo1218** [comment]
@RoseOu 嗯，写API还好，以后写桌面版可能前端同学要搭一个后端环境(现在有ninja不知道要不要了), 要是requirements太多，装的很慢... 之前学而就是这种情况.

**Comment by zxc0328** [comment]
有Ninja就不用搭了哦
