### ISSUE TITLE
这里为什么要decode('ascii')

### ISSUE THREAD

**Issue by neo1218** [Muxi-Studio/guisheng_be#3]
这里: https://github.com/Muxi-Studio/guisheng_be/blob/master/guisheng/app/models.py#L117

拉丁字母的unicode实现本来就是ascii, 这里decode('ascii')没有任何意义
![screen shot 2016-12-05 at 00 12 57](https://cloud.githubusercontent.com/assets/10671733/20867455/9e32d104-ba7f-11e6-9d19-75476fb1cc85.png)

+ 关于python2的字符编码可以看: https://neo1218.github.io/reload/
+ python2和python3字符编码的比较: http://lucumr.pocoo.org/2014/1/5/unicode-in-2-and-3/

**Comment by RoseOu** [comment]
..get..已改 @neo1218
